import { describe, it, expect } from 'vitest';
import { computeTwilioSignature } from '../api/_lib/transport/twilio';

// Reference vector generated by Twilio's own SDK (twilio.getExpectedTwilioSignature)
// and confirmed byte-identical to this implementation — see the cross-check in
// the commit that dropped the `twilio` dependency. This pins that equivalence so
// a future edit can't silently diverge from Twilio's algorithm.
describe('computeTwilioSignature', () => {
  const token = 'sekrit-token-abc123';
  const url = 'https://roca-black.vercel.app/api/webhook';
  const params = {
    From: 'whatsapp:+5511999990000',
    To: 'whatsapp:+14155238886',
    Body: 'posso pulverizar?',
    MessageSid: 'SM123',
    NumMedia: '0',
  };

  it('matches the Twilio SDK reference signature', () => {
    expect(computeTwilioSignature(token, url, params)).toBe('ujPwq8uCXbj1E/4oNKD7ZoiN2jQ=');
  });

  it('is stable regardless of input key order (sorted internally)', () => {
    const reordered = {
      NumMedia: '0',
      Body: 'posso pulverizar?',
      To: 'whatsapp:+14155238886',
      MessageSid: 'SM123',
      From: 'whatsapp:+5511999990000',
    };
    expect(computeTwilioSignature(token, url, reordered)).toBe(
      computeTwilioSignature(token, url, params)
    );
  });

  it('changes when any value changes', () => {
    const tampered = { ...params, Digits: '9999' };
    expect(computeTwilioSignature(token, url, tampered)).not.toBe(
      computeTwilioSignature(token, url, params)
    );
  });
});
